### ISSUE TITLE
Project roadmap

### ISSUE THREAD

**Issue by DannyHatcher-Git** [davish/obsidian-full-calendar#167]
I can see lots of issues but would like to know which ones are your focus right now?

**Comment by davish** [comment]
Unfortunately, I've been dealing with a Repetitive Stress Injury since May and haven't been able to work on the project much since then. My current focus is pull request #103, and after that I hope to address the outstanding issues labeled as bugs that have been submitted.

**Comment by mayurankv** [comment]
It would be really lovely to have a roadmap available in the readme. No worries if that's not something you're interested in doing but I think it would be helpful in clearing up a lot of duplicate FRs and issues.

**Comment by davish** [comment]
@mayurankv feel free to comment on any duplicate feature requests in issues, I try to do my best to clean them up as they're submitted but I'm sure it's not a perfect comparison.

In terms of my roadmap, my focus in the short to medium term is a comprehensive refactor of the plugin in order to make it easier to add new features going forward. The code has become quite a spaghetti mess, and many highly requested features, from more advanced recurrence UI to linked notes two-way CalDAV sync are not possible to implement with the current code architecture.

My hope is that the refactor will make it easier for me to add new features, as well as make it easier for me to accept pull requests from other contributors.

You can see a rough sketch of the roadmap [here](https://github.com/users/davish/projects/2/views/1), but don't expect this to be comprehensive.
