### ISSUE TITLE
You need to select a colour to be able to add a new Google calendar feed

### ISSUE THREAD

**Issue by kmaustral** [davish/obsidian-full-calendar#17]
This can be a problem. Also the option to select Google Calendar extends beyond the window, so you have to know it is there. Small things, but great plugin.

**Comment by kalmir** [comment]
@kmaustral, I have selected a colour yet the sync doesn't work for me. Is there other hitch I should know about? Could you tell me what kind of link Full Calendar expects? Though I have tried pretty much everything from GCal settings page. Including "making calendar public" but I assume that is not necessary, right? Thanks.

**Comment by kalmir** [comment]
There is another potential hitch – esp. for those, like me, don't start with reading the docs as they should (somewhat I thought they won't be updated). I was trying various settings, nothing worked. Because I was always filling in feed **URL**s - as indicated by the relevant field. But in reality Full Calendar expects CalendarID. With CalendarID only, it works.

**Comment by davish** [comment]
Feed URLs should be supported with #27. I'll make sure the default calendar color works before closing this plugin.
