### ISSUE TITLE
Support for obsidian projects plugin

### ISSUE THREAD

**Issue by imeed166** [davish/obsidian-full-calendar#176]
I don't know if you heard about the [projects plugin](https://github.com/marcusolsson/obsidian-projects/issues/27#issuecomment-1299083972). But it wants to [integrate other plugins as views](https://discord.com/channels/686053708261228577/1022167089345216522/1029042785078235187). You can check [this article](https://marcus.se.net/announcing-obsidian-projects/) to get an overview of the plugin.

I would like to suggest adding this plugin as a view to the projects plugin, you can check the [related issue](https://github.com/marcusolsson/obsidian-projects/issues/27#issuecomment-1299083972) or the [custom view API](https://github.com/marcusolsson/obsidian-projects/tree/main/obsidian-projects-types) for context, or you can reach out to the maintainer on discord (marcusolsson#5186), he said he'd be happy to help you in the process.

**Comment by davish** [comment]
As far as I know the projects plugin already has a calendar view. I'm not sure what value it would provide to add a FullCalendar-powered calendar rather than what is offered in the plugin.

On the flip-side, I could see how having Full Calendar events show up in the projects plugin (and vice versa) would be useful. But it doesn't seem like there's an API for custom data sources

**Comment by imeed166** [comment]
@marcusolsson What do you think about supporting custom data sources ?

**Comment by imeed166** [comment]
As for the value, the views are pretty basic, this plugin has more customization. For example, you can't change the time of the event in the day view.

**Comment by davish** [comment]
Have you tried pointing the projects plugin to look at the directory for your events?

**Comment by marcusolsson** [comment]
This looks like an awesome plugin (how did I not know about this before?!)!

> As far as I know the projects plugin already has a calendar view.

You're correct. Though it would be more accurate to consider the built-in calendar as more of a reference implementation to make sure Projects can work as a standalone plugin. It will never be as feature-rich as other dedicated calendar plugins.

For this reason, my ambition is for Projects to connect different views rather than providing them out-of-the-box. In practice, this means that the user configures the data once, and can then reuse it for multiple plugins. Existing plugins will be able to register as views via a hook. Projects then provides the data to the plugin which in turn populates a HTML element inside Projects.

The API for plugins to hook into Projects is still highly experimental with a few plugin authors beta testing it right now. If you're interested you can check out the (again, experimental) [Custom Views API](https://github.com/marcusolsson/obsidian-projects/tree/main/obsidian-projects-types). I'd love to help in any way I can.

> Have you tried pointing the projects plugin to look at the directory for your events?

This works beautifully!

**Comment by davish** [comment]
I can also confirm that creating a new Project with one of your Full Calendar folders as the source, and then adding a calendar view, works well. Closing this issue as it doesn't seem like there's any more work for Full Calendar to support folks using Projects in conjunction. Thanks for filing @imeed166, and thanks for chiming in @marcusolsson!
