### ISSUE TITLE
Make heading leaner

### ISSUE THREAD

**Issue by asmagen** [davish/obsidian-full-calendar#242]
I'm trying to make as much space for my content by minimizing various headers, but the calendar headers are huge.
Can the default be a super lean/thin/minimal header, or at least an option to remove these elements from it?
![Screenshot 2022-12-28 at 6 00 56 PM](https://user-images.githubusercontent.com/11299568/209882977-5b270bd9-535c-456a-8503-a4e66adc34e9.png)

**Comment by drannex42** [comment]
The author has written about how they don't particularly want to invest in the trouble of modifying the core Full Calendar UI. Which is probably a good move.

My solution would be to change the layout using CSS, and Obsidian has a great way for you to do just that. There you can change the font size, and how it lays out (including making it lay out in a column instead of a row). 

This is a [good short article](https://projecteme.medium.com/how-to-customise-your-own-obsidian-css-in-3-steps-ae319e53f5d4) on how to do that.

**Comment by davish** [comment]
This will be fixed as part of #187. You can also open a sidebar calendar if you'd like.

**Comment by squareyed** [comment]
> You can also open a sidebar calendar if you'd like.

Is there another way to open a sidebar calendar besides dragging onto the sidebar from the open calendar tab, or opening with the calendar icon above the sidebar? I tried both, and both ways it still shows the huge text for the date in the sidebar. (Using Windows and Minimal theme.) 

I tried changing the date text with css, but any change to that text changes all the text in Obsidian. That bit of text doesn't appear to have its own html to style. You can't select it in developer mode - when you try, it takes you straight up to <body class=...

The important thing is the plugin works at first glance, and I think it will be extremely helpful even with this current awkwardness. Thank you for that!
