### ISSUE TITLE
Arrow to change Month/Day blacked out after selection

### ISSUE THREAD

**Issue by davebhc71** [davish/obsidian-full-calendar#42]
**To Reproduce**

Arrow to change Month/Day blacked out after selection- see below

![IMG_0664](https://user-images.githubusercontent.com/80698092/156224817-a655d325-bcbb-4312-89f5-ae00cdf4a814.jpeg)

**Device info (please complete the following information):**
 - OS:  iPadOS 15.3
 - Plugin Version 0.5.1

**Comment by davish** [comment]
What theme are you using?

**Comment by davebhc71** [comment]
Minimal

**Comment by davish** [comment]
I'm wondering about how you're loading your theme in, because the font is times new roman rather than the font that Minimal uses. This is happening because your accent color and your text color are the same. I'll certainly work on improving the CSS for the plugin and will reference this issue when I work in it. Thanks for submitting!

**Comment by davebhc71** [comment]
👍, I’ll check the Minimal settings on my end. Thanks for the fast response!
