### ISSUE TITLE
Cache remote calendars locally

### ISSUE THREAD

**Issue by davish** [davish/obsidian-full-calendar#77]
Investigate ways to store local copies of remote calendars to speed up load, while revalidating the calendars from their source in the background (the Stale-While-Revalidating cache strategy).

Be careful not to have this cache sync'd between computers using Obsidian Sync or any other plugin.

**Comment by dojoteef** [comment]
First, according to the [CalDAV RFC](https://datatracker.ietf.org/doc/html/RFC4791#section-8.2.1.3), to synchronize with a CalDAV server you must store off the `ETag` and the URI of the event. The URI actually points to a `.ics` file that represents a calendar with a single event. That's the reason I need an array of `ICalExpander`s in the CalDAV code I wrote (#62). That means at the very least the plugin has to store those two fields for every CalDAV event in the cache to support two-way sync with the server.

Additionally, I did a little sleuthing to see what fields are set on CalDAV events by adding logging. Turns out the fields common to all events are:

```json
[
  "created",
  "uid",
  "dtend",
  "summary",
  "dtstart",
  "dtstamp",
  "last-modified",
  "sequence",
  "transp"
]
```

and here's the full list of fields:
```json
[
  "created",
  "uid",
  "dtend",
  "summary",
  "dtstart",
  "dtstamp",
  "last-modified",
  "sequence",
  "transp",
  "location",
  "description",
  "url",
  "x-apple-structured-location",
  "x-apple-travel-advisory-behavior",
  "status",
  "rrule",
  "x-apple-travel-duration",
  "recurrence-id",
  "related-to",
  "conference",
  "attendee",
  "organizer",
  "attach",
  "exdate",
  "x-apple-suggestion-info-timestamp",
  "x-apple-suggestion-info-opaque-key",
  "x-apple-suggestion-info-unique-key",
  "x-apple-suggestion-info-changed-fields",
  "x-apple-structured-data",
  "x-apple-travel-start",
  "x-microsoft-cdo-ownerapptid",
  "priority",
  "class",
  "x-microsoft-cdo-importance",
  "x-microsoft-cdo-busystatus",
  "x-microsoft-cdo-intendedstatus",
  "x-microsoft-cdo-appt-sequence",
  "x-microsoft-cdo-insttype",
  "x-microsoft-disallow-counter",
  "tzid"
]
```

The plugin can probably ignore any of the `x-` fields as they are vendor specific extensions. It would probably be good to support most of the rest (possibly allowing for a translation layer of both the field name and its value between the frontmatter and the `.ics` data).

One option for cache storage is to allow users to select a directory for CalDAV events (similar to local calendars). The plugin could then store the `.ics` files in that directory. Obsidian sync settings allow people to exclude specific folders and optionally to ignore unknown file types (which this would be since it's not an image, video, audio, or pdf).

With such a setup the plugin could download all the `.ics` during the import phase of adding a new CalDAV calendar. Then it can treat the `.ics` files as the single source of truth for the calendar. Just iterate over the directory and create a list of `ICalExpander`s from the `.ics` files. When someone changes event frontmatter, first make a CalDAV request to update the event and then download the new `.ics` file. When it comes in, notify FullCalendar that the event has been updated. This can be done just by having a file changed watcher. Additionally, by setting FullCalendar's `EventApi.id` to the `.ics` file path, it allows easily mapping between FullCalendar's API and the plugin.

Finally, creating a new event would work similarly. It doesn't get added until an `.ics` file is created from the server that is subsequently downloaded.

What do you think of this approach?

**Comment by davish** [comment]
If we're storing the .ics files locally, I wonder how much more effort it would be to just store the relevant metadata in YAML frontmatter and jump straight to two-way sync? At the very least, we could create notes for each event, and issue a warning `Notice` if users attempt to modify frontmatter that's set by the sync.

**Comment by dojoteef** [comment]
My idea was to delay creating a markdown file for the event until the user tries to edit the event (by clicking on it on the calendar). There will likely be a lot of events if people are syncing their main day-to-day calendars and that would likely clutter up their vault with lots of super old events (I have events going back nearly a decade).

BTW, today I experimented with saving the ics files to disk and it seems to work reasonably well. I need to do a little more work, e.g. deleting the files when you remove the calendar and checking if the etags and ctags have changed so the calendar stays updated. At that point I might put up another PR. This would only be an optimization of the current approach (which downloads the full calendar each time you load the view). Linking CalDAV events to notes can be a separate PR afterward. That would be a stepping stone to two-way sync.
