### ISSUE TITLE
instead of yaml use ```fullcalendar-event

### ISSUE THREAD

**Issue by pcause** [davish/obsidian-full-calendar#82]
Instead or in addition to the yaml, if you allow events in the body enclosed as:

> \```fullcalendar-event
>    
>    ** event details **
>
> \```

you can use the onchange event and see if the file in in the folder for events or one of its subfolers and then extractb events.  you can look at obsidian-itinerary for example code.  this would allow multiple events in a note, compatibility, as you can support both yaml header and in note events with possibly small code changes.

**Comment by davish** [comment]
Hi @pcause,

Thanks for the feature request! The direction I see multiple events in a note is described in #28, and is more in-line with Dataview compatibility than obsidian-itinerary. Even though the itinerary plugin also uses FullCalendar to render calendars, I'm generally not looking to make this plugin a drop-in replacement for Itinerary. it covers a different use case.

Closing this issue, since the feature it's requesting is tracked in #28.

**Comment by pcause** [comment]
I am not trying to push toward being a an itinerary drop in replacement.  just thought some of the ideas there might be useful.  thanks for looking
